apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    {{- include "rest-api-chart.labels" . | nindent 4 }}
data:
  database_url: mongodb-service
  rest_url: mongo-rest-service