apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-rest
  namespace: mongodbhelm
  labels:
    {{- include "rest-api-chart.labels" . | nindent 4 }}
    app: mongo-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-rest
  template:
    metadata:
      labels:
        app: mongo-rest
    spec:
      containers:
      - name: mongo-rest
        image: thecatfishy/restapi
        ports:
        - containerPort: 3000
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: admin-user-password
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: admin-user-password
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url