apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: mongodbhelm
  labels:
    {{- include "common-resources-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: my-mongodb-svc
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}