apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mongodbhelm
  labels:
    app: frontend
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thecatfishy/frontend
        ports:
        - containerPort: 3000
        env:
        - name: ME_CONFIG_REST_API_SERVICE
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: rest_url