apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mongodbhelm
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  selector: 
    app: frontend
  
  ports:
    - name: http
      port: 3000
      nodePort: 30090 # only for NotPort > 30,000  
  type: NodePort #ClusterIP inside cluster