name: Render Helm Chart and Add to Repository
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Setup Helm
     uses: azure/k8s-bake@61041e8c2f75c1f01186c8f05fb8b24e1fc507d8
     with:
       renderEngine: 'helm'
       helmChart: './'
       helm-version: 'latest' 
     id: bake
