name: Run JAR and Update README
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up JDK 17
    uses: actions/setup-java@v2
    with:
      java-version: '17'
      distribution: 'adopt'
  - name: Run JAR
    run: java -jar ./kubeviz-1.0.0-jar-with-dependencies.jar output.yml
  - name: Update README
    run: echo "New text to add to README" >> README.md
  - name: Commit and push if it changed
    run: |
      git diff
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git commit -am "Update README" || exit 0
      git push https://${{ secrets.PAT }}@github.com/TimRoos98/rendering.git

