name: Render Helm Chart and Add to Repository
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: actions/checkout@v2
     uses: azure/k8s-bake@v2.4
     with:
       renderEngine: 'helm'
       helmChart: '.'
       helm-version: 'latest' 
     id: bake
