name: Pihole
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run JAR
        run: java -jar ./kubeviz-1.0.0-jar-with-dependencies.jar github pihole
      - name: Add all new files
        run: git add .
      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "tim.roos.bruijn@gmail.com"
          git config --global user.name "TimRoos98"
          git commit -am "Update README" || exit 0
          git push
